### ISSUE TITLE
Move testing to CircleCI

### ISSUE THREAD

**Issue by wvffle** [PrismarineJS/node-yggdrasil#34]
In most of the projects we use CircleCI, lets then switch from TravisCI

**Comment by rom1504** [comment]
agreed, the way to do it as adding a file like https://github.com/PrismarineJS/prismarine-chunk/blob/master/.circleci/config.yml

**Comment by rom1504** [comment]
superseded by https://github.com/PrismarineJS/node-yggdrasil/issues/43
