### ISSUE TITLE
does not work for node 10 and 12

### ISSUE THREAD

**Issue by MrGeorgen** [PrismarineJS/node-yggdrasil#60]
it works for node 14. Has the support for older versions been dropped?
you can see the error [here](https://github.com/themoonisacheese/2bored2wait/runs/1800982960)

**Comment by extremeheat** [comment]
Why do you need support for those old versions? Usually that's only a concern for browsers. Otherwise the complication target for typescript can be downgraded.

**Comment by MrGeorgen** [comment]
> Why do you need support for those old versions? Usually that's only a concern for browsers. Otherwise the complication target for typescript can be downgraded.

in debian buster stable node 10 is the newest version available

**Comment by u9g** [comment]
> > Why do you need support for those old versions? Usually that's only a concern for browsers. Otherwise the complication target for typescript can be downgraded.
> 
> in debian buster stable node 10 is the newest version available

You can compile typescript down to nodejs 10 https://stackoverflow.com/questions/51716406/typescript-tsconfig-settings-for-node-js-10

**Comment by rom1504** [comment]
You can install any version on debian with nvm

**Comment by MrGeorgen** [comment]
ok thanks
