### ISSUE TITLE
Invalidate endpoint

### ISSUE THREAD

**Issue by ahmedcader** [PrismarineJS/node-yggdrasil#82]
Hello,

Are there plans to add the `/invalidate` endpoint as [seen here](https://wiki.vg/Authentication#Invalidate) in the documentation for Yggdrasil Authentication?

It would be good to have support for the `/invalidate` endpoint because to log out with the existing implementation, a username and password is required and this usually means that these sensitive data will have to be stored somewhere. 

Suppose we don't go that route and use tokens instead, it's much safer and better as it doesn't rely on username and password but just the access and client tokens.

**Comment by ahmedcader** [comment]
@rom1504 have created a PR for this: #83

**Comment by ahmedcader** [comment]
@rom1504 Reopening as these changes are not reflected on the NPM repo. Any chance this can be updated.

**Comment by rom1504** [comment]
yes, do a pr like this https://github.com/PrismarineJS/node-yggdrasil/pull/74/files

**Comment by ahmedcader** [comment]
@rom1504 Thanks, have done. Will close this.
