### ISSUE TITLE
Comment and Function Param List Not Match

### ISSUE THREAD

**Issue by W-Mai** [PrismarineJS/node-yggdrasil#84]
https://github.com/PrismarineJS/node-yggdrasil/blob/95946c9e1fb5d90818d083ad50310d949f64e407/src/Client.js#L8-L12

I found that there was no way to log in to Minecraft correctly when using Mineflayer. When I traced the source code, I found that ```yggdrasil.auth()``` was called in minecraft-protocol, and the ```cb``` function was passed. However, ```yggdrasil.auth()``` did not have two parameters, nor did Use the ```cb``` function.

Please fix, thanks.

**Comment by rom1504** [comment]
Do you have an error?

**Comment by W-Mai** [comment]
Though there's no error, it doesn't work correctly.

Your comment has two parameters, but the function has one.

And if you read the code of ```minecraft-protocol```, it shows passing two parameters into this ```yggdrasil.auth()``` method.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-yggdrasil/blob/master/src/Client.js#L67

**Comment by W-Mai** [comment]
I'm sorry,
This is an interesting coding trick
